### ISSUE TITLE
Uso de leaflet con Argenmap

### ISSUE THREAD

**Issue by jonathan-barbero** [ign-argentina/argenmap-leaflet-ign-tpl#10]
Vi los ejemplos de Argenmap donde requiere usar una versión especial de jquery, lo que dificulta la posibilidad de integrarlo en un sitio donde ya se usa otra versión de jquery.
Este proyecto donde usan leaflet me gusto.

- Podrían dar un ejemplo de como se puede usar desde otro sitio con leaflet ?

- Si se usa Argenmap desde un sitio como el de Banco Nación, abría algún problema?

**Comment by Zalitoar** [comment]
Gracias por el issue @jonathan-barbero 

La [página de Argenmap](https://www.ign.gob.ar/argenmap2/argenmap.jquery/docs/index.html) disponible en el sitio web principal del IGN hace referencia a una versión embebible que aunque funciona bien ya quedó obsoleta porque está basada en OpenLayers 2 entre otras cosas. Además como decís depende de JQuery.

El visualizador basado en Leaflet, que sería una nueva "versión" de [Argenmap](https://github.com/ign-argentina/argenmap) fue pensado como un visualizador de mapas de página completa y no empotrable, sin embargo sería útil contar con algo así hecho con software más "actual". Por el momento todavía no tenemos planificado hacer algo así pero si sumamos tu necesidad a la nuestra tendríamos más motivos para poder empezar a pensar en algo.

Una opción es que hagas un mapa simple con Leaflet u OpenLayers que tenga como mapa base al que publica el IGN por TMS: 
`https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/capabaseargenmap@EPSG%3A3857@png/{z}/{x}/{y}.png`

Te sugerimos continuar este tema contactándonos a argenmap (at) ign.gob.ar para ver cómo podríamos darte una mano con respecto a un visualizador empotrable como el que mencionas.

Saludos,
Gonzalo
